### ISSUE TITLE
Converting your code to work with Calendar api

### ISSUE THREAD

**Issue by longestdrive** [thujohn/analytics-l4#1]
Hi - thanks for your code - I hope you don't mind but I'm trying to modify your code to use the google calendar api. I keep falling at first hurdles! This is not an issue for your code more a plea for help :)

I am using your analytics.php as a start, have set up a workbench in laravel 4 and included your package as a dependancy - I can get your package to work in my workbench.
However in my googlecal.php file (my name for the package) which is almost identical to yours I come up with an error:

```
Argument 1 passed to Longestdrive\Googlecal\Googlecal::__construct() must be an instance of Google_Client, none given
```

So I assume it can't create a google_client. My service provider register is identical to yours.
As my project is still in workbench and your package is in the vendor folder does this make any difference to the path I need to specify to google_client? which is currently:

```
public function __construct(\Google_Client $client) {
        $this->setClient($client);
        $this->setService($client);
    }
```

Sorry - I'm fairly new to L4 and this is my first attempt at a package so struggling all the way!
Appreciate any tips or pointers please

**Comment by thujohn** [comment]
Hi.

Do you include bitgandtter/google-api ?

The error happen in your ServiceProvider.
Check my method register() : https://github.com/thujohn/analytics-l4/blob/master/src/Thujohn/Analytics/AnalyticsServiceProvider.php#L43

There is no difference working in workbench except for publishing config/assets.

**Comment by longestdrive** [comment]
Thank you. Yes I had included after all the effort it was an error in the service provider register function. I omitted to include $client - doh.
Thanks
