### ISSUE TITLE
Non-static method

### ISSUE THREAD

**Issue by ghost** [thujohn/analytics-l4#18]
I'm trying to use the example in the README but this is what returns:

Non-static method Thujohn\Analytics\Analytics::getSiteIdByUrl() should not be called statically, assuming $this from incompatible context

**Comment by rayne128** [comment]
Did you try adding this in your config/app.php?

```
         'providers' => array(
            ...
            'Thujohn\Analytics\AnalyticsServiceProvider'
        );

        'aliases' => array(
            ...
            'Analytics' => 'Thujohn\Analytics\AnalyticsFacade'
        );
```

Then you can just use the method by  `Analytics::getAllSitesIds();`

**Comment by saleamp** [comment]
Yes, I have those in my app.php file. This is the code I'm trying to run:

```
...
use Thujohn\Analytics\Analytics;

class GoogleController extends AdminController {

    public static function analytics() {

        $sites = Analytics::getAllSitesIds();

        return $sites;

    }
...
```

Then calling it in a blade file:

```
$results = GoogleController::analytics();

print_r($results);
```

**Comment by rayne128** [comment]
Try removing
`use Thujohn\Analytics\Analytics;`
on your GoogleController class

**Comment by saleamp** [comment]
I did, but it's looking for the class in my extension. For example:

```
Class '<Extension>\<Extension Name>\Controllers\Admin\Analytics' not found
```

**Comment by thujohn** [comment]
You need to use the facade

``` php
use \Thujohn\Analytics\AnalyticsFacade as Analytics;
```

or just

``` php
use \Analytics;
```

**Comment by saleamp** [comment]
That works. Thanks!
