### ISSUE TITLE
Is there any way to authenticate other than using Service Account?

### ISSUE THREAD

**Issue by rayne128** [thujohn/analytics-l4#19]
As the subject states. Is there any other way of using the tool other than adding the service email to the user's google analytics account? Thanks in advance.

**Comment by alenn-m** [comment]
I would like to know this as well

**Comment by thujohn** [comment]
Hi.

I made this package to simply create an app and not manage authorizations after.

What "other way" would you have ?

**Comment by rayne128** [comment]
thanks for replying thujohn, I was thinking an oAuth way or something but nonethless very cool and useful package. cheers.
