### ISSUE TITLE
All implemented but I obtain always the same error

### ISSUE THREAD

**Issue by a-p-co** [thujohn/analytics-l4#3]
Hi! I have the bundle installed on my laravel 4.0 and all the conf is right, but I have an error when I call this route:

ROUTE:
Route::get('/list', function()
{
  return print_r(Analytics::webproperties()->listManagementWebproperties("~all"));
});

ERROR:
The Response content must be a string or object implementing __toString(), "boolean" given.

I also try:

ROUTE
Route::get('/list', function()
{
  return Analytics::webproperties()->listManagementWebproperties("~all"));
});

ERROR:
The Response content must be a string or object implementing __toString(), "object" given.

Any idea? Thanks

**Comment by thujohn** [comment]
Hi.

Sorry for the delay.

When you have an error like this try dd() ;)

``` php
Route::get('/list', function()
{
    $accounts = Analytics::webproperties()->listManagementWebproperties("~all");
    foreach ($accounts as $account){
        var_dump($account);
    }
});
```

**Comment by a-p-co** [comment]
Don't worry and thanks you very much for the answer, It works perfectly!
