### ISSUE TITLE
Install/update issue requiring google/apiclient 1.1.*

### ISSUE THREAD

**Issue by GC-Mark** [thujohn/analytics-l4#30]
Since the latest commit, I keep getting the following error on `composer update`

``` shell
- thujohn/analytics dev-master requires google/apiclient 1.1.* -> no matching package found.
- Installation request for thujohn/analytics dev-master -> satisfiable by thujohn/analytics[dev-master].
```

I can see that the package required should be satisfied. Not sure why it isn't working though :confused: 

https://packagist.org/packages/google/apiclient

**Comment by thujohn** [comment]
And now ?

**Comment by GC-Mark** [comment]
Same

``` shell
- thujohn/analytics dev-master requires google/apiclient 1.1.*@dev -> no matching package found.
- Installation request for thujohn/analytics dev-master -> satisfiable by thujohn/analytics[dev-master].
```

**Comment by thujohn** [comment]
It works for me...

What is the value of "minimum-stability" ?

**Comment by GC-Mark** [comment]
Normally set to `stable` but I have also tried it set to `dev` with the same outcome :confused:

**Comment by thujohn** [comment]
Can you try to just install `"google/apiclient": "1.1.*"` ?

**Comment by GC-Mark** [comment]
Doh, finally figured it out, in my `composer.json`, i already had `"google/apiclient": "1.0.*@beta",` defined.

I stared at my `composer.json` file for ages today and I never noticed that! Don't even know why it was there!

Sorry, my bad!
